trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Azure Cypress Run'
  jobs:
  - job: Build
    displayName: 'Install Node.js and Run Cypress'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npx cypress run
      displayName: 'Install dependencies and run Cypress tests'
