trigger:
- main

pool:
  name: 'learnAzure'

stages:
- stage: Build
  displayName: 'Azure Cypress Run'
  jobs:
  - job: Build
    displayName: 'Install Node.js and Run Cypress'
    pool:
      name: 'learnAzure'  
    demands:
      - Agent.Name -equals az400learn
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npx cypress run
      displayName: 'Install dependencies and run Cypress tests'
